config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # ViewComponent styleguide routes (only in development and test)
  if Rails.env.local?
    get '/styleguide', to: 'styleguide#index', as: :styleguide
    get '/styleguide/*path', to: 'styleguide#previews', as: :styleguide_preview
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show] do
    member do
      post :follow, to: 'follows#create'
      delete :unfollow, to: 'follows#destroy'
      get :followers
      get :following
      get :raffles
    end
  end

  resource :profile, only: [:show], controller: 'users'
  get 'feed', to: 'feed#index', as: :feed
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'raffles#index'

  resources :raffles, only: %i[index show new create] do
    collection do
      get :completed
    end
    resources :raffle_tickets, only: [:create], path: 'tickets'
  end

  resource :wallet, only: [:show]
  resources :my_created_raffles, only: [:index]
  resources :my_participating_raffles, only: [:index]
  resources :my_tickets, only: [:index], controller: 'raffle_tickets'
  resources :referrals, only: [:index]

  namespace :admin do
    root to: 'admin#index'
    resources :raffles, only: [] do
      member do
        post :cancel
        post :toggle_auto_draw
        post :hand_over
      end
    end
    resources :users, only: [] do
      member do
        post :ban
        post :unban
      end
    end
  end
end

app/models/follow.rb
# frozen_string_literal: true

class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, uniqueness: { scope: :followed_id }
  validate :not_self_follow

  after_create :create_follow_activity, :check_achievements

  private

  def not_self_follow
    errors.add(:follower_id, 'cannot follow yourself') if follower_id == followed_id
  end

  def create_follow_activity
    UserActivity.create_follow_activity(follower, followed)
  end

  def check_achievements
    Achievement.check_and_award_achievements(followed)
  end
end

app/controllers/follows_controller.rb
# frozen_string_literal: true

class FollowsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def create
    current_user.follow!(@user)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to user_path(@user), notice: "You are now following #{@user.email}" }
    end
  end

  def destroy
    current_user.unfollow!(@user)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to user_path(@user), notice: "You unfollowed #{@user.email}" }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/follows/create.turbo_stream.erb
<%= turbo_stream.replace "user-profile-actions-#{@user.id}" do %>
  <%= turbo_frame_tag "user-profile-actions-#{@user.id}" do %>
    <div class="is-flex is-justify-content-center is-align-items-center mb-4" style="gap: 1rem;">
      <%= link_to followers_user_path(@user), class: "has-text-centered", data: { turbo: false } do %>
        <p class="has-text-weight-semibold" id="followers-count-<%= @user.id %>"><%= @user.reload.followers.count %></p>
        <p class="is-size-7 has-text-grey">Followers</p>
      <% end %>
      <%= link_to following_user_path(@user), class: "has-text-centered", data: { turbo: false } do %>
        <p class="has-text-weight-semibold" id="following-count-<%= @user.id %>"><%= @user.reload.followings.count %></p>
        <p class="is-size-7 has-text-grey">Following</p>
      <% end %>
    </div>

    <div class="buttons is-centered">
      <% if @user == current_user %>
        <% action_buttons = [
          { label: "Edit Profile", path: "#", class: "is-light" },
          { label: "Settings", path: "#", class: "is-light" }
        ] %>
        <% action_buttons.each do |button| %>
          <%= link_to button[:label], button[:path], class: "button #{button[:class]} is-small", data: { turbo: false } %>
        <% end %>
      <% else %>
        <%= link_to "View Raffles", raffles_user_path(@user), class: "button is-primary is-small", data: { turbo: false } %>
        <%= render partial: 'shared/follow_button', locals: { user: @user.reload, button_size: 'is-small', button_style: nil } %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/follows/destroy.turbo_stream.erb
<%= turbo_stream.replace "user-profile-actions-#{@user.id}" do %>
  <%= turbo_frame_tag "user-profile-actions-#{@user.id}" do %>
    <div class="is-flex is-justify-content-center is-align-items-center mb-4" style="gap: 1rem;">
      <%= link_to followers_user_path(@user), class: "has-text-centered", data: { turbo: false } do %>
        <p class="has-text-weight-semibold" id="followers-count-<%= @user.id %>"><%= @user.reload.followers.count %></p>
        <p class="is-size-7 has-text-grey">Followers</p>
      <% end %>
      <%= link_to following_user_path(@user), class: "has-text-centered", data: { turbo: false } do %>
        <p class="has-text-weight-semibold" id="following-count-<%= @user.id %>"><%= @user.reload.followings.count %></p>
        <p class="is-size-7 has-text-grey">Following</p>
      <% end %>
    </div>

    <div class="buttons is-centered">
      <% if @user == current_user %>
        <% action_buttons = [
          { label: "Edit Profile", path: "#", class: "is-light" },
          { label: "Settings", path: "#", class: "is-light" }
        ] %>
        <% action_buttons.each do |button| %>
          <%= link_to button[:label], button[:path], class: "button #{button[:class]} is-small", data: { turbo: false } %>
        <% end %>
      <% else %>
        <%= link_to "View Raffles", raffles_user_path(@user), class: "button is-primary is-small", data: { turbo: false } %>
        <%= render partial: 'shared/follow_button', locals: { user: @user.reload, button_size: 'is-small', button_style: nil } %>
      <% end %>
    </div>
  <% end %>
<% end %>